In [14]:
import numpy as np

In [15]:
s = np.array([[0.73, 0.02, 0.25], [0.1, 0.8, 0.1], [0.25, 0.02, 0.73]])

In [16]:
x = np.array([35, 150, 35])

In [17]:
for i in range(100):
    x = np.dot(s.T, x)
    print(x)
    

[ 49.3 121.4  49.3]
[60.454 99.092 60.454]
[69.15412 81.69176 69.15412]
[75.9402136 68.1195728 75.9402136]
[81.23336661 57.53326678 81.23336661]
[85.36202595 49.27594809 85.36202595]
[88.58238024 42.83523951 88.58238024]
[91.09425659 37.81148682 91.09425659]
[93.05352014 33.89295972 93.05352014]
[94.58174571 30.83650858 94.58174571]
[95.77376165 28.45247669 95.77376165]
[96.70353409 26.59293182 96.70353409]
[97.42875659 25.14248682 97.42875659]
[97.99443014 24.01113972 97.99443014]
[98.43565551 23.12868898 98.43565551]
[98.7798113  22.44037741 98.7798113 ]
[99.04825281 21.90349438 99.04825281]
[99.25763719 21.48472561 99.25763719]
[99.42095701 21.15808598 99.42095701]
[99.54834647 20.90330706 99.54834647]
[99.64771025 20.70457951 99.64771025]
[99.72521399 20.54957202 99.72521399]
[99.78566691 20.42866617 99.78566691]
[99.83282019 20.33435962 99.83282019]
[99.86959975 20.2608005  99.86959975]
[99.89828781 20.20342439 99.89828781]
[99.92066449 20.15867102 99.92066449]
[99.9381183 20.1237